name: Run Shell Script and Capture Output

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run script and set output
        id: script
        run: |
          chmod +x ./.github/workflows/scripts/release.sh
          echo "OUTPUT=$(./.github/workflows/scripts/release.sh)" >> $GITHUB_ENV

      - name: Use the output
        run: echo "The script output was '${{ env.OUTPUT }}'"
